app_api_crud_index:
    path: /api/{resourcePath}/
    controller: App\Cruding\Controller\Api\Crud\CrudApiIndexController
    methods: [GET]
    defaults:
        _crud_operation: index
        _crud_surface: public
    requirements:
        resourcePath: '[a-z0-9/_-]+'

app_api_crud_create:
    path: /api/{resourcePath}/
    controller: App\Cruding\Controller\Api\Crud\CrudApiCreateController
    methods: [POST]
    defaults:
        _crud_operation: create
        _crud_surface: public
    requirements:
        resourcePath: '[a-z0-9/_-]+'

app_api_crud_show_slug:
    path: /api/{resourcePath}/{slug}
    controller: App\Cruding\Controller\Api\Crud\CrudApiShowController
    methods: [GET]
    defaults:
        _crud_operation: show
        _crud_surface: public
    requirements:
        resourcePath: '[a-z0-9/_-]+'
        slug: '[A-Za-z0-9][A-Za-z0-9_-]*'

app_api_crud_update_slug:
    path: /api/{resourcePath}/{slug}
    controller: App\Cruding\Controller\Api\Crud\CrudApiUpdateController
    methods: [PUT, PATCH]
    defaults:
        _crud_operation: update
        _crud_surface: public
    requirements:
        resourcePath: '[a-z0-9/_-]+'
        slug: '[A-Za-z0-9][A-Za-z0-9_-]*'

app_api_crud_delete_slug:
    path: /api/{resourcePath}/{slug}
    controller: App\Cruding\Controller\Api\Crud\CrudApiDeleteController
    methods: [DELETE]
    defaults:
        _crud_operation: delete
        _crud_surface: public
    requirements:
        resourcePath: '[a-z0-9/_-]+'
        slug: '[A-Za-z0-9][A-Za-z0-9_-]*'
