app_crud_new:
    path: /{resourcePath}/new/
    controller: App\Cruding\Controller\Crud\CrudCreateController
    methods: [GET, POST]
    defaults:
        _crud_operation: new
        _crud_surface: public
    requirements:
        resourcePath: '[a-z0-9/_-]+'

app_crud_edit_id:
    path: /{resourcePath}/edit/{id}
    controller: App\Cruding\Controller\Crud\CrudEditController
    methods: [GET, POST]
    defaults:
        _crud_operation: edit
        _crud_surface: admin
    requirements:
        resourcePath: '[a-z0-9/_-]+'
        id: '\d+'

app_crud_edit_slug:
    path: /{resourcePath}/edit/{slug}
    controller: App\Cruding\Controller\Crud\CrudEditController
    methods: [GET, POST]
    defaults:
        _crud_operation: edit
        _crud_surface: public
    requirements:
        resourcePath: '[a-z0-9/_-]+'
        slug: '[A-Za-z0-9][A-Za-z0-9_-]*'

app_crud_delete_id:
    path: /{resourcePath}/delete/{id}
    controller: App\Cruding\Controller\Crud\CrudDeleteController
    methods: [POST]
    defaults:
        _crud_operation: delete
        _crud_surface: admin
    requirements:
        resourcePath: '[a-z0-9/_-]+'
        id: '\d+'

app_crud_delete_slug:
    path: /{resourcePath}/delete/{slug}
    controller: App\Cruding\Controller\Crud\CrudDeleteController
    methods: [POST]
    defaults:
        _crud_operation: delete
        _crud_surface: public
    requirements:
        resourcePath: '[a-z0-9/_-]+'
        slug: '[A-Za-z0-9][A-Za-z0-9_-]*'

app_crud_show_id:
    path: /{resourcePath}/{id}
    controller: App\Cruding\Controller\Crud\CrudShowController
    methods: [GET]
    defaults:
        _crud_operation: show
        _crud_surface: admin
    requirements:
        resourcePath: '[a-z0-9/_-]+'
        id: '\d+'

app_crud_show_slug:
    path: /{resourcePath}/{slug}
    controller: App\Cruding\Controller\Crud\CrudShowController
    methods: [GET]
    defaults:
        _crud_operation: show
        _crud_surface: public
    requirements:
        resourcePath: '[a-z0-9/_-]+'
        slug: '[A-Za-z0-9][A-Za-z0-9_-]*'

app_crud_index:
    path: /{resourcePath}/
    controller: App\Cruding\Controller\Crud\CrudIndexController
    methods: [GET]
    defaults:
        _crud_operation: index
        _crud_surface: public
    requirements:
        resourcePath: '[a-z0-9/_-]+'
