cruding_new:
    path: /{resourcePath}/new/
    controller: App\Cruding\Controller\Crud\CrudCreateController
    methods: [GET, POST]
    defaults:
        _crud_operation: new
        _crud_surface: public
    requirements:
        resourcePath: '%cruding.resource_path_requirement%'

cruding_edit_id:
    path: /{resourcePath}/edit/{id}
    controller: App\Cruding\Controller\Crud\CrudEditController
    methods: [GET, POST]
    defaults:
        _crud_operation: edit
        _crud_surface: admin
    requirements:
        resourcePath: '%cruding.resource_path_requirement%'
        id: '\d+'

cruding_edit_slug:
    path: /{resourcePath}/edit/{slug}
    controller: App\Cruding\Controller\Crud\CrudEditController
    methods: [GET, POST]
    defaults:
        _crud_operation: edit
        _crud_surface: public
    requirements:
        resourcePath: '%cruding.resource_path_requirement%'
        slug: '[A-Za-z0-9][A-Za-z0-9_-]*'

cruding_delete_id:
    path: /{resourcePath}/delete/{id}
    controller: App\Cruding\Controller\Crud\CrudDeleteController
    methods: [POST]
    defaults:
        _crud_operation: delete
        _crud_surface: admin
    requirements:
        resourcePath: '%cruding.resource_path_requirement%'
        id: '\d+'

cruding_delete_slug:
    path: /{resourcePath}/delete/{slug}
    controller: App\Cruding\Controller\Crud\CrudDeleteController
    methods: [POST]
    defaults:
        _crud_operation: delete
        _crud_surface: public
    requirements:
        resourcePath: '%cruding.resource_path_requirement%'
        slug: '[A-Za-z0-9][A-Za-z0-9_-]*'

cruding_show_id:
    path: /{resourcePath}/{id}
    controller: App\Cruding\Controller\Crud\CrudShowController
    methods: [GET]
    defaults:
        _crud_operation: show
        _crud_surface: public
    requirements:
        resourcePath: '%cruding.resource_path_requirement%'
        id: '\d+'

cruding_show_slug:
    path: /{resourcePath}/{slug}
    controller: App\Cruding\Controller\Crud\CrudShowController
    methods: [GET]
    defaults:
        _crud_operation: show
        _crud_surface: public
    requirements:
        resourcePath: '%cruding.resource_path_requirement%'
        slug: '[A-Za-z0-9][A-Za-z0-9_-]*'

cruding_index:
    path: /{resourcePath}/
    controller: App\Cruding\Controller\Crud\CrudIndexController
    methods: [GET]
    defaults:
        _crud_operation: index
        _crud_surface: public
    requirements:
        resourcePath: '%cruding.resource_path_requirement%'

cruding_index_root:
    path: /{resourcePath}
    controller: App\Cruding\Controller\Crud\CrudIndexController
    methods: [GET]
    defaults:
        _crud_operation: index
        _crud_surface: public
    requirements:
        resourcePath: '%cruding.resource_path_requirement%'
